### ISSUE TITLE
Feedback from Koray Tecimer

### ISSUE THREAD

**Issue by korayt** [UBC-MDS/DSCI-532_2024_20_hotspot#37]
Overall very nice and informative plots. It it easy to understand. Color choices are very good and works well. There is sorting in the plot which makes it easier to compare.
Points of feedback (areas to improve):
- Temperature and CO2 Emissions over Time plot's x axis is year but the formatted like it is a continuous decimal number. example: 2,023.0 -> 2023
- After selecting countries or the date range sometimes it takes a long time for plots to update and it is not clear if the page is updating. Maybe a submit button would make it more obvious that we should wait for the plots to load.
- A nicer map could've been selected looking at the other groups that has maps they used a map that is more interactive.
- Creating borders for plots could be better as there is a white background and it be better organized.
- It doesn't allow me to select a date range <20 years, that could be improved.
- Maybe for audiance to compare the carbon emission of individual countries there could be also a statistic for mean carbon emissions for countries that could be plotted. The plots would allow an individual country to be compared with the rest.

**Comment by monazhu** [comment]
- Temperature and CO2 Emissions over Time plot's x axis is year but the formatted like it is a continuous decimal number. example: 2,023.0 -> 2023
   - Change implemented as part of Milestone 3 ✅ 
- After selecting countries or the date range sometimes it takes a long time for plots to update and it is not clear if the page is updating. Maybe a submit button would make it more obvious that we should wait for the plots to load.
   - Sped up operation using paraquat file; loading animation added to signal chart being updated ✅ 
- A nicer map could've been selected looking at the other groups that has maps they used a map that is more interactive.
   - Map interactivity implemented as part of Milestone 3 ✅ 
- Creating borders for plots could be better as there is a white background and it be better organized.
   - Dashboard layout optimized as part of Milestone 3 ✅ 
- It doesn't allow me to select a date range <20 years, that could be improved.
   - The restricted range is intentional (i.e., we need sufficient range in order to plot a trend of CO2 and temperature change over time) ✖️ 
- Maybe for audiance to compare the carbon emission of individual countries there could be also a statistic for mean carbon emissions for countries that could be plotted. The plots would allow an individual country to be compared with the rest.
   - mean statistic is not very informative in the context of CO2 emission, since there can be huge variability over time (e.g., China) ✖️
