### ISSUE TITLE
Feedback from Yi Yan

### ISSUE THREAD

**Issue by carrieyanyi** [UBC-MDS/DSCI-532_2024_20_hotspot#48]
The overall dashboard looks well functional. Some points may be considered in the future improvement:

- [ ] The bar chart shows the CO2 emission based on each country, while the line chart I guess is cumulative. It would be easy to navigate if separating the line chart for comparison or changing the title so that readers can easily follow.
- [ ] Might add a card for the 'Total CO2 emissions', instead of using plain text. 
- [ ] Header font size could be differentiated from the filter option, and the 'filter option' font size now is larger than 'Total CO2 emissions', which could also be adjusted.
- [ ] Add a background color to the title might help to grab a reader's attention about the dashboard topic.
- [ ] Too much whitespace, a good suggestion might use a color theme.

**Comment by monazhu** [comment]
- The bar chart shows the CO2 emission based on each country, while the line chart I guess is cumulative. It would be easy to navigate if separating the line chart for comparison or changing the title so that readers can easily follow.
   - Considering that all of our plots updated given the (1) year range and (2) countries selected, we decided to make it extra clear by including this information in our sidebar widget ✅ 
-  Might add a card for the 'Total CO2 emissions', instead of using plain text.
   - We tried a card implementation of this, but it actually ended up looking too busy. To keep our dashboard clean/simple, we decided to retain the current layout (but moved the `Total CO2 emission` section to the middle so it's clearly separated from the rest of the input widgets ✅ 
-  Header font size could be differentiated from the filter option, and the 'filter option' font size now is larger than 'Total CO2 emissions', which could also be adjusted.
   - Thanks for the suggestion! We've adjusted the header font size throughout the dashboard ✅ 
-  Add a background color to the title might help to grab a reader's attention about the dashboard topic.
   - We attempted to add a background colour to the title, but it ended up making our dashboard look too clunky/busy. The current layout (greyed out widget + white background everywhere else) was the most optimal dashboard layout after testing a few different combinations ✅ 
-  Too much whitespace, a good suggestion might use a color theme.
   - We adjusted the sizes of the plots and changed the dashboard layout to reduce the amount of extra/unnecessary white spaces throughout ✅

**Comment by monazhu** [comment]
Closing issue as all comments have been addressed
