### ISSUE TITLE
Feedback from Rory White

### ISSUE THREAD

**Issue by rorywhite200** [UBC-MDS/DSCI-532_2024_20_hotspot#55]
Hello group 20, I love your dashboard. It's really impressive and I like the concept of visualizing CO2 emissions. It's a good counterpoint to our dashboard which helps people emit by flying.

Here is my feedback for how you could make it more useful:

- Some of the filtering, for instance by year, is quite slow. Could you speed that up by indexing columns or something like that?
- Consider implementing a toggle between total emissions and per capita emissions to provide a fairer representation
- The map visualization and bar chart is very red, you could consider a wider color range with yellow colours too to enable a more intuitive understanding for the user.
-  You could pair the color range on the map with the range on the bar chart, so countries are the same color on both.
- When you click on one country on the map it filters to that, but if you click on another afterwards it doesn't update. You could consider implementing that so it updates.
- If possible, you could try to fit it on a single view, so that it doesn't require scrolling to see the whole dashboard. You could do this by making it responsive to the screen size.
- It doesn't seem possible to select an individual year. I think that for some policy uses people will definitely want to look at a single calendar year, so you could update your slider to allow this if possible.

**Comment by juliaeveritt** [comment]
Thanks so much for this helpful feedback Rory!

**Comment by monazhu** [comment]
Thanks for the feedback Rory! Below are our responses to your suggestions: 

- Some of the filtering, for instance by year, is quite slow. Could you speed that up by indexing columns or something like that?
   - We've optimized the dashboard as much as we can (i.e., having a pre-processed/cleaned paraquet file and implementing memory caching) but there is still some lag as a result of how large the dataset was. We've added a loading animation to help our users' expectations as plots update ✅ 
- Consider implementing a toggle between total emissions and per capita emissions to provide a fairer representation
   - Thanks for the suggestion! As this additional callback might be a bit more involved, we decided on a middle ground for the current implementation, by having an additional plot (i.e., cumulative CO2 emission per country per capita). ✅ 
- The map visualization and bar chart is very red, you could consider a wider color range with yellow colours too to enable a more intuitive understanding for the user.
   - We changed the default red colour scale to a custom colour scale that incorporates more orange/yellow to help distinguish the colours a bit more. We also implemented a log-scale for the colour range so that the countries in the middle of the range can be more easily distinguished from one another ✅ 
- You could pair the color range on the map with the range on the bar chart, so countries are the same color on both.
   - We thought about the implementation of this detail, but decided against implementing it, as the top emitters would have very slightly different shades of red, which might not look all that different from what we currently have ✖️ 
- When you click on one country on the map it filters to that, but if you click on another afterwards it doesn't update. You could consider implementing that so it updates.
   - We made box select our current default, which gets around this issue ✅ 
- If possible, you could try to fit it on a single view, so that it doesn't require scrolling to see the whole dashboard. You could do this by making it responsive to the screen size.
   - Thanks for this suggestion! The screen size responsivity is a bit tricky given the final layout we decided on. This is something we're hoping to look into for future implementations, time permitting ✖️ 
- It doesn't seem possible to select an individual year. I think that for some policy uses people will definitely want to look at a single calendar year, so you could update your slider to allow this if possible.
   - We understand that this is an important aspect that policy makers might be interested in, however, the restricted year range is an intention decision, as we wanted to showcase the trendline plot of temperature/CO2 over time, for the current implementation of the dashboard ✖️
