### ISSUE TITLE
Feedback from Bill Wan

### ISSUE THREAD

**Issue by billwan96** [UBC-MDS/DSCI-532_2024_20_hotspot#56]
Hello Group 20~ 

The dashboard looks great and informative, I learnt a lot from you guys!
In general, the app is very intuitive to use and well-suited to the usage scenario. While I primarily evaluated the deployed website on onrender, which might not be the most updated version, below are some suggestions and observations:

1. CO2 Emission Bar Chart: It would be beneficial to include the total emissions of each country alongside the emissions per capita. Might be a fairer comparison and provide users with additional context to identify regions with higher emissions.
2. Year Range: might be nice to display the selected year range, either through the range slider tooltip or beneath the total CO2 emission card. So that users might have a clearer picture of what they have filtered.
3. Map Tooltip: the map's iso_code tooltips, I'm uncertain about their necessity.
4. Line Graph: It was a bit unclear upon initial inspection. To enhance clarity, it could be beneficial to explicitly indicate that the temperature change is related to CO2 emissions.
5. Plot Titles: would be nice to make the plot titles reflect the selected filter options would be beneficial. e.g. titling a plot as "Temperature and CO2 Emissions over Time in Russia"

Some sidenotes:
- I like that the red theme effectively conveys the severity and urgency of the environmental issues addressed by the dashboard.
- I also like the way you show how huge the GTs emission is equivalent to.

**Comment by monazhu** [comment]
Thank you very much for your comments/suggestions Bill! Below are our responses to your comments: 

- CO2 Emission Bar Chart: It would be beneficial to include the total emissions of each country alongside the emissions per capita. Might be a fairer comparison and provide users with additional context to identify regions with higher emissions.
   - We have added an additional plot (Emission per capita for top emitters) to help provide users with additional context ✅ 
- Year Range: might be nice to display the selected year range, either through the range slider tooltip or beneath the total CO2 emission card. So that users might have a clearer picture of what they have filtered.
   - We implemented this in the current iteration of the dashboard (under our "Total CO2 Emission" card, we now showcase the exact year range) ✅ 
- Map Tooltip: the map's iso_code tooltips, I'm uncertain about their necessity.
   - Thank you for the suggestion. As this is a more minor point/does not affect the usability of the dashboard too much, we decided to deprioritize it for the current implementation of the dashboard ✖️ 
- Line Graph: It was a bit unclear upon initial inspection. To enhance clarity, it could be beneficial to explicitly indicate that the temperature change is related to CO2 emissions.
   - We did not want to use the dashboard to draw too much conclusion for our users; this correlation is something that we hope the users will be able to pick up on their own. However, we did add additional context around the key metrics used for this particular plot, as there is more info compared to other plots, to help our users understand what it is that we are showcaseing ✅ 
- Plot Titles: would be nice to make the plot titles reflect the selected filter options would be beneficial. e.g. titling a plot as "Temperature and CO2 Emissions over Time in Russia"
   - We decided against implementing this, as the title would become quite long/clunky when many different countries are selected (it also gets a bit redundant when we need to do this for all 3 plots). The sidebar widget does also already provide this information. ✖️
